name: Feature request
description: An idea to make LiquidDo even better
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: Idea
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why it would help
